openapi: "3.0.0"
info:
  title: Cyber Demonstrator Server
  description: |
    An OpenAPI spec of the @nqminds/cyber-demonstrator-server API
  contact:
    name: "NquiringMinds"
    email: "info@nquiringminds.com"
    url: "https://nquiringminds.com/contact/"
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Development Server
paths:
  /vulnerability-analysis:
    post:
      summary: Upload and analyze a file for vulnerability assessment
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successfully analyzed the file
        '400':
          description: Bad Request
          content:
            text/plain:
              example: No file uploaded
            application/json:
              example: { error: "The file is not a valid CycloneDX JSON" }
        '500':
          description: Internal Server Error
          content:
            application/json:
              example: { error: "Internal server error" }
